#!/bin/bash

unset GEM_HOME
unset GEM_PATH

CREW_FILE_DIR=$(dirname $0)
CREW_HOST_OS=`uname -s | tr '[:upper:]' '[:lower:]'`

if [ -z $SSL_CERT_FILE ]; then
    SSL_CERT_FILE="$CREW_FILE_DIR/etc/ca-certificates.crt"
fi

if [ -z $CREW_NDK_DIR ]; then
    CREW_NDK_DIR=$CREW_FILE_DIR/../..
fi

if [ -z $CREW_TOOLS_DIR ]; then
    CREW_HOST_CPU=`uname -m`
    if [ ! -d "$CREW_NDK_DIR/prebuilt/$CREW_HOST_OS-$CREW_HOST_CPU" ]; then
        CREW_HOST_CPU=${CREW_HOST_CPU%_64}
    fi
    CREW_TOOLS_DIR="$CREW_NDK_DIR/prebuilt/$CREW_HOST_OS-$CREW_HOST_CPU"
fi

if [ -f $CREW_TOOLS_DIR/bin/ruby ]; then
    CREW_RUBY=$CREW_TOOLS_DIR/bin/ruby
else
    echo "Warning: using system ruby"
    CREW_RUBY=ruby
fi

export SSL_CERT_FILE
export CREW_NDK_DIR

exec $CREW_RUBY -W0 "$CREW_FILE_DIR/crew.rb" "$@"
